services:
  - type: web
    name: shelter-api
    env: docker
    dockerfilePath: docker/Dockerfile
    healthCheckPath: /api/v1/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: LOG_FORMAT
        value: json
      - key: CORS_ORIGINS
        value: https://admin-dashboard-ruby-phi.vercel.app
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "6543"
      - key: DB_NAME
        value: postgres
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: shelter-redis
          property: connectionString
      - key: RESEND_API_KEY
        sync: false
      - key: EMAIL_FROM
        value: Shelter <noreply@mail.shelterfaithapps.xyz>
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true

  - type: redis
    name: shelter-redis
    plan: free
    maxmemoryPolicy: allkeys-lru
    ipAllowList: []
