import type { Knex } from 'knex';

export async function seed(knex: Knex): Promise<void> {
  await knex('devotional_completions').del();
  await knex('devotionals').del();
  await knex('streaks').del();

  const today = new Date();
  const devotionals = Array.from({ length: 30 }, (_, i) => {
    const date = new Date(today);
    date.setDate(date.getDate() - (29 - i));
    const dateStr = date.toISOString().split('T')[0];

    const devotionals_list = [
      {
        title: 'Finding Peace in the Storm',
        scripture_reference: 'John 14:27',
        scripture_text: 'Peace I leave with you; my peace I give you. I do not give to you as the world gives. Do not let your hearts be troubled and do not be afraid.',
        reflection: 'In a world that often feels chaotic, Jesus offers us a peace that transcends circumstances. This peace is not the absence of trouble but the presence of Christ in the midst of it. When we anchor our hearts in Him, the storms of life may rage around us, but our inner world can remain calm. Today, take a moment to breathe deeply and receive the peace that only He can give.',
        closing_prayer: 'Lord, thank You for Your peace that surpasses all understanding. In the midst of my busy day, help me to pause and receive the calm assurance that comes from You. Quiet my anxious heart and fill me with Your perfect peace. Amen.',
        author: 'Grace Wilson',
        is_published: true,
      },
      {
        title: 'The Power of Gratitude',
        scripture_reference: '1 Thessalonians 5:16-18',
        scripture_text: 'Rejoice always, pray continually, give thanks in all circumstances; for this is God\'s will for you in Christ Jesus.',
        reflection: 'Gratitude has the power to transform our perspective. When we choose to give thanks in all circumstances, we acknowledge that God is at work even in the difficult seasons. Gratitude shifts our focus from what we lack to what we have been given. It is not about denying our struggles but about recognizing God\'s faithfulness through them.',
        closing_prayer: 'Father, cultivate a heart of gratitude within me. Help me to see Your hand in every situation and to give thanks not just for the good days, but for the ways You grow me through the hard ones. Amen.',
        author: 'David Shepherd',
        is_published: true,
      },
      {
        title: 'Walking in Faith, Not Fear',
        scripture_reference: 'Isaiah 41:10',
        scripture_text: 'So do not fear, for I am with you; do not be dismayed, for I am your God. I will strengthen you and help you; I will uphold you with my righteous right hand.',
        reflection: 'Fear has a way of paralyzing us and keeping us from stepping into God\'s purposes for our lives. But again and again, Scripture reminds us that we serve a God who goes before us. He does not simply call us to be brave on our own strength. He promises to be with us, to strengthen us, and to uphold us. When fear knocks at your door today, let faith answer.',
        closing_prayer: 'God, when I am afraid, help me to remember that You are with me. Give me the courage to trust Your plan even when I cannot see the outcome. Hold me steady in Your unfailing love. Amen.',
        author: 'Sarah Hope',
        is_published: true,
      },
      {
        title: 'Abiding in the Vine',
        scripture_reference: 'John 15:4-5',
        scripture_text: 'Remain in me, as I also remain in you. No branch can bear fruit by itself; it must remain in the vine. Neither can you bear fruit unless you remain in me. I am the vine; you are the branches. If you remain in me and I in you, you will bear much fruit; apart from me you can do nothing.',
        reflection: 'There is a profound freedom in acknowledging that we are not meant to do life on our own. Just as a branch draws its life from the vine, we are designed to draw our strength, wisdom, and purpose from Christ. When we try to produce fruit in our own effort, we quickly become burned out and discouraged. But when we remain in Him, fruit naturally grows as a byproduct of our connection.',
        closing_prayer: 'Jesus, teach me what it means to truly abide in You. Help me to stop striving and start resting in Your presence. May my life naturally bear fruit as I stay connected to You. Amen.',
        author: 'Michael Faith',
        is_published: true,
      },
      {
        title: 'A Heart of Forgiveness',
        scripture_reference: 'Colossians 3:12-13',
        scripture_text: 'Therefore, as God\'s chosen people, holy and dearly loved, clothe yourselves with compassion, kindness, humility, gentleness and patience. Bear with each other and forgive one another if any of you has a grievance against someone. Forgive as the Lord forgave you.',
        reflection: 'Forgiveness is one of the hardest yet most freeing commands we are given. Holding onto unforgiveness is like drinking poison and expecting the other person to suffer. When we forgive, we are not saying what happened was okay. We are freeing ourselves from the burden of bitterness and trusting God to bring justice and healing in His way and His time.',
        closing_prayer: 'Lord, search my heart and reveal any unforgiveness I may be holding onto. Give me the strength to release it to You. Help me to extend the same grace to others that You have so generously extended to me. Amen.',
        author: 'Rebecca Peace',
        is_published: true,
      },
      {
        title: 'Strength in Weakness',
        scripture_reference: '2 Corinthians 12:9-10',
        scripture_text: 'But he said to me, "My grace is sufficient for you, for my power is made perfect in weakness." Therefore I will boast all the more gladly about my weaknesses, so that Christ\'s power may rest on me.',
        reflection: 'Our culture tells us to hide our weaknesses and project strength at all times. But God works differently. He invites us to bring our weaknesses to Him because it is in those very places that His power shines brightest. When we admit we cannot do it alone, we create space for God to move. Your weakness is not a liability in the Kingdom. It is an opportunity for His strength to be displayed.',
        closing_prayer: 'Father, I confess that I often try to hide my weaknesses. Help me to embrace them as opportunities for Your power to be made perfect. Let Your strength be evident in my life today. Amen.',
        author: 'Grace Wilson',
        is_published: true,
      },
      {
        title: 'The Lord is My Shepherd',
        scripture_reference: 'Psalm 23:1-4',
        scripture_text: 'The Lord is my shepherd, I lack nothing. He makes me lie down in green pastures, he leads me beside quiet waters, he refreshes my soul. He guides me along the right paths for his name\'s sake. Even though I walk through the darkest valley, I will fear no evil, for you are with me; your rod and your staff, they comfort me.',
        reflection: 'Psalm 23 is perhaps the most beloved passage of Scripture, and for good reason. It paints a picture of God as a tender Shepherd who cares for every need of His sheep. Sheep are not particularly strong or intelligent animals. They are completely dependent on their shepherd. In the same way, we are invited to trust in God\'s provision and guidance completely. He leads us, restores us, and walks with us even through the darkest valleys.',
        closing_prayer: 'Lord, thank You for being my Shepherd. Help me to trust Your leading even when I cannot see the path ahead. Restore my soul and guide me in the way I should go. Amen.',
        author: 'Shelter Team',
        is_published: true,
      },
      {
        title: 'Hope That Does Not Disappoint',
        scripture_reference: 'Romans 5:3-5',
        scripture_text: 'Not only so, but we also glory in our sufferings, because we know that suffering produces perseverance; perseverance, character; and character, hope. And hope does not put us to shame, because God\'s love has been poured out into our hearts through the Holy Spirit, who has been given to us.',
        reflection: 'Paul presents a counterintuitive chain reaction: suffering leads to perseverance, which builds character, which deepens hope. This is not a hope that crosses its fingers and wishes for the best. This is a confident expectation rooted in God\'s proven faithfulness. When we have walked through suffering and seen God meet us there, our hope becomes unshakable.',
        closing_prayer: 'God, when I face trials, help me to see them as opportunities for growth. Develop in me perseverance and character, and anchor my hope firmly in You. Amen.',
        author: 'David Shepherd',
        is_published: true,
      },
      {
        title: 'Created for Good Works',
        scripture_reference: 'Ephesians 2:10',
        scripture_text: 'For we are God\'s handiwork, created in Christ Jesus to do good works, which God prepared in advance for us to do.',
        reflection: 'You are not an accident or an afterthought. You are God\'s handiwork, His masterpiece, created with intention and purpose. Before you were even born, God prepared specific good works for you to walk in. Your life has meaning that extends beyond your job, your relationships, or your accomplishments. You were created on purpose for a purpose.',
        closing_prayer: 'Lord, thank You that I am Your handiwork. Show me the good works You have prepared for me today. Give me eyes to see the opportunities to serve and love others that You place in my path. Amen.',
        author: 'Michael Faith',
        is_published: true,
      },
      {
        title: 'Be Still and Know',
        scripture_reference: 'Psalm 46:10',
        scripture_text: 'He says, "Be still, and know that I am God; I will be exalted among the nations, I will be exalted in the earth."',
        reflection: 'In a world that never stops moving, the command to "be still" can feel almost impossible. Yet this is exactly what our souls need. Being still is not about physical inactivity but aboutPosture of the heart. It is choosing to stop striving, stop worrying, and stop trying to control everything. In the stillness, we remember Who God is and that He is in control. We do not have to carry the weight of the world on our shoulders.',
        closing_prayer: 'Father, quiet my restless heart. Help me to be still in Your presence and to know deeply that You are God. I release my worries and my need for control into Your capable hands. Amen.',
        author: 'Sarah Hope',
        is_published: true,
      },
      {
        title: 'Love One Another',
        scripture_reference: 'John 13:34-35',
        scripture_text: 'A new command I give you: Love one another. As I have loved you, so you must love one another. By this everyone will know that you are my disciples, if you love one another.',
        reflection: 'Jesus gave His disciples a new commandment, and it was not about building large ministries or achieving great things. It was about love. The world would know we belong to Him not by our theology or our activities but by our love for one another. This love is not a feeling but a choice demonstrated through action. It is patient, kind, and sacrificial. Today, look for an opportunity to love someone the way Jesus has loved you.',
        closing_prayer: 'Jesus, help me to love others the way You have loved me. Give me a heart of compassion and the courage to show Your love through my actions today. Amen.',
        author: 'Shelter Team',
        is_published: true,
      },
      {
        title: 'Casting Your Cares',
        scripture_reference: '1 Peter 5:6-7',
        scripture_text: 'Humble yourselves, therefore, under God\'s mighty hand, that he may lift you up in due time. Cast all your anxiety on him because he cares for you.',
        reflection: 'Peter gives us a beautiful exchange: we humble ourselves, and God lifts us up. We cast our anxieties on Him, and He carries them because He cares for us. The image of casting is active and intentional. It is not passively hoping our worries go away but actively releasing them to God. Whatever you are carrying today, He is strong enough to hold it. You do not have to bear the weight alone.',
        closing_prayer: 'Lord, I bring my anxieties to You. I lay them at Your feet and choose to trust You with the things I cannot control. Thank You that You care for me and that I do not have to carry this burden alone. Amen.',
        author: 'Rebecca Peace',
        is_published: true,
      },
      {
        title: 'New Every Morning',
        scripture_reference: 'Lamentations 3:22-23',
        scripture_text: 'Because of the Lord\'s great love we are not consumed, for his compassions never fail. They are new every morning; great is your faithfulness.',
        reflection: 'One of the most beautiful truths of our faith is that God\'s mercies are new every morning. No matter what happened yesterday, today is a fresh start. God does not run out of compassion or patience with us. His faithfulness is not dependent on our performance. Every sunrise is a reminder that His love is constant and His grace is sufficient for whatever today holds.',
        closing_prayer: 'Thank You, Lord, that Your mercies are new every morning. Help me to receive Your grace today and to extend that same grace to others. Great is Your faithfulness. Amen.',
        author: 'Grace Wilson',
        is_published: true,
      },
      {
        title: 'The Armor of God',
        scripture_reference: 'Ephesians 6:10-11',
        scripture_text: 'Finally, be strong in the Lord and in his mighty power. Put on the full armor of God, so that you can take your stand against the devil\'s schemes.',
        reflection: 'Paul reminds us that we are in a spiritual battle, but we are not defenseless. God has provided everything we need to stand firm: the belt of truth, the breastplate of righteousness, the shoes of peace, the shield of faith, the helmet of salvation, and the sword of the Spirit. We do not need to be afraid because we do not fight in our own strength. We fight with the armor God provides.',
        closing_prayer: 'Father, help me to put on the full armor of God today. Give me strength to stand firm against the challenges I face, knowing that You have provided everything I need. Amen.',
        author: 'David Shepherd',
        is_published: true,
      },
      {
        title: 'Pray Without Ceasing',
        scripture_reference: 'Philippians 4:6-7',
        scripture_text: 'Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God. And the peace of God, which transcends all understanding, will guard your hearts and your minds in Christ Jesus.',
        reflection: 'Prayer is not just a religious ritual. It is a lifeline that connects us to the God who loves us. Paul encourages us to bring everything to God in prayer, not just the big things but every situation. When we exchange our anxiety for prayer, God gives us something better than we asked for: His peace that transcends understanding. This peace guards our hearts and minds, keeping us steady no matter what comes.',
        closing_prayer: 'Lord, I choose to bring everything to You in prayer. I release my anxiety and receive Your peace. Guard my heart and mind today in Christ Jesus. Amen.',
        author: 'Michael Faith',
        is_published: true,
      },
      {
        title: 'Living in Community',
        scripture_reference: 'Hebrews 10:24-25',
        scripture_text: 'And let us consider how we may spur one another on toward love and good deeds, not giving up meeting together, as some are in the habit of doing, but encouraging one another — and all the more as you see the Day approaching.',
        reflection: 'We were not designed to walk the Christian life alone. Community is not optional, it is essential. When we gather together, we encourage one another, spur each other on, and remind each other of God\'s faithfulness. In a world that often isolates us, choosing to stay connected to the body of Christ is an act of faith and obedience.',
        closing_prayer: 'God, thank You for the gift of community. Help me to stay connected to Your people and to be an encouragement to those around me. Teach me to spur others on toward love and good deeds. Amen.',
        author: 'Sarah Hope',
        is_published: true,
      },
      {
        title: 'Trust in the Lord',
        scripture_reference: 'Proverbs 3:5-6',
        scripture_text: 'Trust in the Lord with all your heart and lean not on your own understanding; in all your ways submit to him, and he will make your paths straight.',
        reflection: 'Trusting God with all our hearts means surrendering our need to have everything figured out. It is acknowledging that His ways are higher than our ways and His thoughts higher than our thoughts. When we stop relying solely on our own understanding and submit our plans to Him, He guides our steps. The path may not always be easy, but it leads to where He wants us to go.',
        closing_prayer: 'Lord, I trust You with all my heart. I will not lean on my own understanding. Guide my steps today and make my path straight as I submit to Your will. Amen.',
        author: 'Rebecca Peace',
        is_published: true,
      },
      {
        title: 'The Fruit of the Spirit',
        scripture_reference: 'Galatians 5:22-23',
        scripture_text: 'But the fruit of the Spirit is love, joy, peace, forbearance, kindness, goodness, faithfulness, gentleness and self-control. Against such things there is no law.',
        reflection: 'The fruit of the Spirit is not something we produce by trying harder. It is the natural result of walking in step with the Holy Spirit. As we spend time in God\'s presence, His character begins to shape ours. Love, joy, peace, patience, kindness, goodness, faithfulness, gentleness, and self-control grow in our lives not through effort but through abiding.',
        closing_prayer: 'Holy Spirit, cultivate Your fruit in my life. Make me more like Jesus today in my thoughts, words, and actions. Amen.',
        author: 'Shelter Team',
        is_published: true,
      },
      {
        title: 'Do Not Grow Weary',
        scripture_reference: 'Galatians 6:9',
        scripture_text: 'Let us not become weary in doing good, for at the proper time we will reap a harvest if we do not give up.',
        reflection: 'Sometimes doing the right thing feels exhausting. We wonder if our efforts matter or if anyone notices. But God sees every act of kindness, every prayer prayed in secret, every step of obedience. He promises that there will be a harvest if we do not give up. The timing is His, but the reward is certain. Keep going. Your labor in the Lord is not in vain.',
        closing_prayer: 'Father, when I feel weary, renew my strength. Help me to persevere in doing good, trusting that You see and You will reward in Your perfect timing. Amen.',
        author: 'Grace Wilson',
        is_published: true,
      },
      {
        title: 'God is Our Refuge',
        scripture_reference: 'Psalm 46:1-3',
        scripture_text: 'God is our refuge and strength, an ever-present help in trouble. Therefore we will not fear, though the earth give way and the mountains fall into the heart of the sea, though its waters roar and foam and the mountains quake with their surging.',
        reflection: 'The psalmist paints a picture of absolute chaos: the earth giving way, mountains falling, waters roaring. Yet in the midst of it, God is our refuge and strength. He is not just a distant observer of our struggles but an ever-present help. When everything around us feels unstable, He is the solid ground beneath our feet.',
        closing_prayer: 'God, You are my refuge and strength. When everything around me feels chaotic, help me to find my stability in You. Be my ever-present help today. Amen.',
        author: 'David Shepherd',
        is_published: true,
      },
      {
        title: 'The Greatest Commandment',
        scripture_reference: 'Mark 12:30-31',
        scripture_text: 'Love the Lord your God with all your heart and with all your soul and with all your mind and with all your strength. The second is this: Love your neighbor as yourself. There is no commandment greater than these.',
        reflection: 'Jesus distilled the entire law into two simple commands: love God completely and love others as yourself. Everything else flows from these. When we get these right, everything else falls into place. Today, ask yourself: am I loving God with my whole being? Am I loving my neighbor as myself? These are the measurements of a life well lived.',
        closing_prayer: 'Lord, help me to love You with all my heart, soul, mind, and strength. And help me to love my neighbors as myself. Let my life be defined by love. Amen.',
        author: 'Michael Faith',
        is_published: true,
      },
      {
        title: 'Joy in the Morning',
        scripture_reference: 'Psalm 30:5',
        scripture_text: 'For his anger lasts only a moment, but his favor lasts a lifetime; weeping may stay for the night, but rejoicing comes in the morning.',
        reflection: 'The Christian life is not exempt from pain and sorrow. Weeping may endure for the night, but joy comes in the morning. This is the rhythm of grace: sorrow gives way to joy, darkness gives way to light, death gives way to resurrection. Whatever you are walking through tonight, hold on. Morning is coming.',
        closing_prayer: 'Lord, when I am in the midst of sorrow, help me to hold on to the promise that joy is coming. Give me strength to endure the night, knowing that morning will come. Amen.',
        author: 'Sarah Hope',
        is_published: true,
      },
      {
        title: 'Called to Serve',
        scripture_reference: 'Mark 10:45',
        scripture_text: 'For even the Son of Man did not come to be served, but to serve, and to give his life as a ransom for many.',
        reflection: 'Jesus redefined greatness. In the world, greatness is measured by how many people serve you. In the Kingdom, greatness is measured by how many people you serve. Jesus, the King of Kings, washed His disciples\' feet. If He came to serve, then we are called to do the same. Today, look for opportunities to serve others with humility and love.',
        closing_prayer: 'Jesus, teach me to be a servant like You. Give me a humble heart that looks for ways to serve others. Help me to put their needs above my own. Amen.',
        author: 'Rebecca Peace',
        is_published: true,
      },
      {
        title: 'By Grace Through Faith',
        scripture_reference: 'Ephesians 2:8-9',
        scripture_text: 'For it is by grace you have been saved, through faith — and this is not from yourselves, it is the gift of God — not by works, so that no one can boast.',
        reflection: 'Salvation is a gift, not a wage. We cannot earn it, and we do not deserve it. It is freely given by God\'s grace and received through faith. This truth is the foundation of our faith. We do not have to perform or strive for God\'s approval. We are already fully loved and fully accepted because of what Jesus has done. Rest in that today.',
        closing_prayer: 'Father, thank You for the gift of salvation. Help me to receive Your grace fully and to live from a place of rest, not striving. I am saved by grace through faith, and that is enough. Amen.',
        author: 'Shelter Team',
        is_published: true,
      },
      {
        title: 'The Good Shepherd',
        scripture_reference: 'John 10:10-11',
        scripture_text: 'The thief comes only to steal and kill and destroy; I have come that they may have life, and have it to the full. I am the good shepherd. The good shepherd lays down his life for the sheep.',
        reflection: 'Jesus contrasts His mission with the enemy\'s. The enemy comes to steal, kill, and destroy. Jesus came to give life in all its fullness. Not a life free from problems, but a life rich with meaning, purpose, and connection to God. As the Good Shepherd, He does not just tend to us from a distance. He lays down His life for us. That is the depth of His love.',
        closing_prayer: 'Jesus, thank You for being my Good Shepherd. Thank You for laying down Your life for me. Help me to receive the abundant life You offer and to follow Your voice today. Amen.',
        author: 'Grace Wilson',
        is_published: true,
      },
      {
        title: 'Wait on the Lord',
        scripture_reference: 'Isaiah 40:31',
        scripture_text: 'But those who wait on the Lord will renew their strength. They will soar on wings like eagles; they will run and not grow weary, they will walk and not be faint.',
        reflection: 'Waiting is not passive. In Scripture, waiting on the Lord is an active posture of trust and expectation. When we wait on God, we are not sitting around doing nothing. We are actively trusting, praying, and positioning ourselves to receive what He has promised. And the promise is clear: He will renew our strength. What feels like waiting is actually preparation.',
        closing_prayer: 'Lord, teach me to wait on You with expectant faith. Renew my strength as I put my trust in You. Help me to soar on wings like eagles today. Amen.',
        author: 'David Shepherd',
        is_published: true,
      },
      {
        title: 'Do Not Be Anxious',
        scripture_reference: 'Matthew 6:25-27',
        scripture_text: 'Therefore I tell you, do not worry about your life, what you will eat or drink; or about your body, what you will wear. Is not life more than food, and the body more than clothes? Look at the birds of the air; they do not sow or reap or store away in barns, and yet your heavenly Father feeds them. Are you not much more valuable than they?',
        reflection: 'Jesus invites us to consider the birds. They do not worry about tomorrow, yet God provides for them. How much more will He care for us, who are made in His image and redeemed by His Son? Worry does not add a single hour to our lives, but trusting God changes everything. Release your worries to the One who holds tomorrow.',
        closing_prayer: 'Father, help me to trust You with my needs. When I am tempted to worry, remind me of the birds and Your faithful provision. I am valuable to You, and You will take care of me. Amen.',
        author: 'Michael Faith',
        is_published: true,
      },
      {
        title: 'Redeemed and Restored',
        scripture_reference: 'Joel 2:25-26',
        scripture_text: 'I will repay you for the years the locusts have eaten — the great locust and the young locust, the other locusts and the locust swarm. You will have plenty to eat, until you are full, and you will praise the name of the Lord your God, who has worked wonders for you.',
        reflection: 'God is a redeemer. He does not just forgive our sins. He restores what has been lost. The locusts represent the years of devastation, the time we feel we have wasted, the opportunities that slipped away. God promises to repay those years. He is not limited by our past. He is the God of restoration, and He is able to bring beauty from ashes.',
        closing_prayer: 'Lord, I trust You to redeem the years that have been lost. Restore what the enemy has stolen and bring beauty from the ashes of my life. I praise You for Your faithfulness. Amen.',
        author: 'Sarah Hope',
        is_published: true,
      },
      {
        title: 'The Light of the World',
        scripture_reference: 'Matthew 5:14-16',
        scripture_text: 'You are the light of the world. A town built on a hill cannot be hidden. Neither do people light a lamp and put it under a bowl. Instead they put it on its stand, and it gives light to everyone in the house. In the same way, let your light shine before others, that they may see your good deeds and glorify your Father in heaven.',
        reflection: 'Jesus does not say you "should" be the light of the world. He says you "are" the light of the world. It is not something you have to achieve; it is something you already are because He lives in you. Your job is not to create light but to let the light that is already within you shine. Do not hide it. The world needs the hope and love that God has placed in you.',
        closing_prayer: 'Jesus, thank You that I am light in You. Help me to shine brightly today so that others may see Your love through me and glorify our Father in heaven. Amen.',
        author: 'Rebecca Peace',
        is_published: true,
      },
      {
        title: 'Finished Work',
        scripture_reference: 'John 19:30',
        scripture_text: 'When he had received the drink, Jesus said, "It is finished." With that, he bowed his head and gave up his spirit.',
        reflection: 'Three words from the cross changed everything. "It is finished." Not "it is beginning" or "it is almost done." It is finished. The work of salvation was complete. Jesus paid the full price for every sin, past, present, and future. There is nothing left for us to add. We do not work for our salvation; we work from it. Rest in the finished work of Christ today.',
        closing_prayer: 'Lord, thank You that it is finished. Thank You that I do not have to earn or strive for Your love. Help me to rest in the completed work of the cross and to live from that place of grace. Amen.',
        author: 'Shelter Team',
        is_published: true,
      },
    ];

    return {
      id: undefined,
      title: devotionals_list[i]?.title ?? `Devotional ${dateStr}`,
      scripture_reference: devotionals_list[i]?.scripture_reference ?? 'Psalm 118:24',
      scripture_text: devotionals_list[i]?.scripture_text ?? 'This is the day the Lord has made; let us rejoice and be glad in it.',
      reflection: devotionals_list[i]?.reflection ?? 'Each day is a gift from God. When we wake up with gratitude and intentionality, we position ourselves to receive all that He has for us. Today is an opportunity to encounter His love in new ways.',
      closing_prayer: devotionals_list[i]?.closing_prayer ?? 'Lord, thank You for this day. Help me to live it fully for Your glory. Amen.',
      published_date: dateStr,
      author: devotionals_list[i]?.author ?? 'Shelter Team',
      is_published: devotionals_list[i]?.is_published ?? true,
      created_at: new Date(),
      updated_at: new Date(),
    };
  });

  await knex('devotionals').insert(devotionals);
}
